matrix:
  n_enroll_spk: 22024
  seeds: [42, 0,  6, 7, 25]
  enroll_path: "data/embs_libri_ECAPA_orig/embs_avg_cv11-A_ECAPA_921_orig.pkl"
  trial_path: "data/embs_libri_ECAPA_orig/spk2embs_cv11-B_ECAPA_921_orig_ids.pkl"
  model_type: "libri_ECAPA_orig"
  data_type: "VAD_orig"