matrix:
  n_enroll_spk: 22024
  seeds: [42, 0,  6, 7, 25]
  enroll_path: "data/embs_avg_cv11-A_VAD_resnet_libri-54_anon_B3_V2.pkl"
  trial_path: "data/spk2embs_cv11-B_VAD_resnet_libri-54_anon_B3_V2.pkl"
  model_type: "libri_ECAPA_B3_V2"
  data_type: "VAD_anon_B3_V2"